### PR TITLE
Some hardcoded strings in gamemd

### PR DESCRIPTION
**Pull request by chaserli**
Some strings in gamemd, like "rulesmd.ini"

### CODE REVIEW

**Comment by chaserli** [comment]
@Metadorius were you suggesting this?
BTW Am I using the template correctly for this one?

**Comment by Metadorius** [comment]
Yeah, that's what I meant. Should be, does it work?

**Comment by chaserli** [comment]
> Yeah, that's what I meant. Should be, does it work?

I only tested with that `EVA_OreMinerUnderAttack` in `ShiedClass.cpp`, it worked as expected but in my IDA the decompiler didn't show `MEMORY[0x824784]` but `(const char*)0x824784`

**Comment by chaserli** [comment]
> > Yeah, that's what I meant. Should be, does it work?
> 
> I only tested with that `EVA_OreMinerUnderAttack` in `ShiedClass.cpp`, it worked as expected but in my IDA the decompiler didn't show `MEMORY[0x824784]` but `(const char*)0x824784`

Wait... It should behave like that, otherwise it's wrong. So rn when using these it will behave like using `reinterpret_cast<const char*>(addr)` in-place.

**Pull request merged**
